### PR TITLE
Reservation Changes

### PR DESCRIPTION
**Pull request by aumoore**
… adding updated war file that includes updates to reservation page and edits to the CSS page

### CODE REVIEW

**Comment by JKBrown11** [comment]
Hey Austin, 
I don't think we need to keep using war files for updates. I'm worried that instead of updating the files in the repo, it will just mismatch, like with a new war and old files. Or did you try to merge everything you changed? (It's showing only .war file updated)
I was thinking the war file would help us get the project accessible in Eclipse, and then we can just update the source files like we would while working alone, just from a branch. Again, I'm not sure what you attempted. I've not used this much before outside of the basic class assignments.

**Comment by aumoore** [comment]
I updated only the CSS and Reservation JSP...I can see if I can export those files individually and then upload them versus uploading the entire .war file? I just thought since I have adjustments to Tomcat and had to add in an extra JSTL file, I should upload the entire .war file. But I'm not quite sure which route is the best one?

**Comment by JKBrown11** [comment]
So when you do a pull request, you should get a new copy of the whole project to make changes to. Then you re-sync the whole project with a push and we review the changes to see if we're going to switch to your new version. So I would expect to see the changes to the 'original ' CSS and reservation documents on this branch to review the code. We wont need an updated war until we submit the website. The versions here won't be file names, just commits.

**Review by JKBrown11 — APPROVED** [review]
Hey, I think we're good, just a new folder.

**Pull request merged**
